project_id = "dlwyndcvnunvomgkbkhn"

[functions.create-album-checkout]
verify_jwt = true

[functions.track-event]
verify_jwt = false

[functions.analyze-user-behavior]
verify_jwt = true

[functions.merchant-chat]
verify_jwt = true

[functions.fan-chat]
verify_jwt = false

[functions.shopify-products]
verify_jwt = false
