project_id = "dlwyndcvnunvomgkbkhn"

[functions.create-album-checkout]
verify_jwt = true

[functions.track-event]
verify_jwt = false

[functions.analyze-user-behavior]
verify_jwt = true

[functions.merchant-chat]
verify_jwt = true

[functions.fan-chat]
verify_jwt = false

[functions.shopify-products]
verify_jwt = false

[functions.set-thumbnail]
verify_jwt = false

[functions.update-thumbnail]
verify_jwt = false

[functions.analyze-content-performance]
verify_jwt = true

[functions.process-scheduled-cameos]
verify_jwt = false

[functions.create-cameo-checkout]
verify_jwt = false
